#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
nitrogen --restore &
dunst &
powerkit &
lxsession &
# picom --experimental-backends -b --animations --animation-for-open-window zoom &
xrdb ~/.Xresources &
sleep 1 &
~/.config/polybar/launch.sh &

xsetroot -cursor_name left_ptr

bspc monitor -d     

bspc config border_width 2
bspc config window_gap 5

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"

bspc config focus_follows_pointer true
bspc config pointer_modifier super

bspc rule -a TelegramDesktop desktop='^4'
